version: '3.9'

services:
  reconftw:
    container_name: reconftw
    build:
      context: .
      dockerfile: Dockerfile
  volumes:
    - reconftw-data:/var/lib/data/
  ports:
    - 5000:5000
volumes:
  reconftw-data:
